name: "Build package"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-latest, macos-latest ]
        python-version: [ "3.0", "3.1", "3.2", "3.3", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13" ]
        exclude:
          - os: ubuntu-20.04
            python-version: "3.0"
          - os: ubuntu-20.04
            python-version: "3.1"
          - os: ubuntu-20.04
            python-version: "3.2"
          - os: ubuntu-20.04
            python-version: "3.3"
          - os: ubuntu-20.04
            python-version: "3.4"
          - os: macos-latest
            python-version: "3.0"
          - os: macos-latest
            python-version: "3.1"
          - os: macos-latest
            python-version: "3.2"
          - os: macos-latest
            python-version: "3.3"
          - os: macos-latest
            python-version: "3.4"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
          architecture: x64
      - name: Install build requirements
        run: |
          python -m pip install -U pip
      - name: Build package linux
        run: |
          if [[ "${{ matrix.python-version }}" =~ ^3\.[0-6]$ ]]; then
            echo "Legacy setup.py build"
            python -m pip install setuptools
            python setup.py install
          else
            echo "PEP 517 build"
            python -m pip install build
            python -m build
          fi
        if: "${{ matrix.os }}" == "ubuntu-20.04" || "${{ matrix.os }}" == "macos-latest"
      - name: Build package windows
        shell: cmd
        run: |
          python -m pip install build
          python -m build
        if: "${{ matrix.os }}" == "windows-latest"
